{% set name = "psiresp" %}
{% set version = "0.4.0" %}

package:
  name: psiresp-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ed7504bf89aa6c76aedc35005382e461ef61809b9dd64e64cf6b55c61dc57321

build:
  number: 0

outputs:
  - name: psiresp-base
    
    build:
      noarch: python
    script: install_base.sh
    
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - python >=3.7
        - qcelemental
        - numpy
        - scipy >=1.4
        - tqdm
    
    test:
      imports:
      - psiresp
      files:
        - test_basic_psiresp.py
      commands:
        - python test_basic_psiresp.py

  - name: psiresp
    build:
      noarch: python

    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - python >=3.7
        - geometric
        - rdkit
        - qcfractal
        - requests
        - h5py <3.2
        - {{ pin_subpackage('psiresp-base', exact=True) }}
    
    test:
      imports:
        - psiresp
      files:
        - test_rdkit_psiresp.py
      commands:
        - python test_rdkit_psiresp.py


about:
  home: https://github.com/lilyminium/psiresp
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: 'Calculate RESP charges with Psi4'
  description: |
    PsiRESP is a package for calculating atomic partial charges
    from restrained and unrestrained electrostatic potential fits.
    The electrostatic potentials can be calculated using QCFractal
    and Psi4, or provided.
  doc_url: https://psiresp.readthedocs.io/
  dev_url: https://github.com/lilyminium/psiresp

extra:
  recipe-maintainers:
    - lilyminium
